CREATE SCHEMA IF NOT EXISTS test;
USE test;

DROP TABLE IF EXISTS FOOD;
CREATE TABLE FOOD (FOOD_ID BIGINT PRIMARY KEY AUTO_INCREMENT, FOOD_NAME VARCHAR(80), FOOD_TYPE VARCHAR (100), FOOD_EXOTIC BIT );

INSERT INTO FOOD (FOOD_ID,FOOD_NAME,FOOD_TYPE,FOOD_EXOTIC) VALUES (5,'fdsf','овощ',true);
